### ISSUE TITLE
TypeError: integer argument expected, got float?

### ISSUE THREAD

**Issue by Basavaraj-PN** [Gogul09/gesture-recognition#1]
Traceback (most recent call last):
  File "recognize.py", line 169, in <module>
    fingers = count(thresholded, segmented)
  File "recognize.py", line 78, in count
    cv2.circle(circular_roi, (cX, cY), radius, 255, 1)
TypeError: integer argument expected, got float

**Comment by avidLearnerInProgress** [comment]
@basavaraj1995 
Typecast cX, cY and circular_roi to integer. You can do it using numpy:

` np.round(argument).astype("int")`

where argument is cX/ cY/ circular_roi

**Comment by Catastrophe101** [comment]
change line 78 to cv2.circle(circular_roi, (int(cX), int(cY)), int(radius), 255, 1)

**Comment by CooperPair** [comment]
you can also do the changes at the line number 59 and 60 that is 
```
cX = (extreme_left[0] + extreme_right[0]) // 2
cY = (extreme_top[1] + extreme_bottom[1]) // 2
```
since it is asking for integer value.

**Comment by Basavaraj-PN** [comment]
thanks
